version: "2.4"

services:
  original_web_server:
    image: "httpd:2.4"
    container_name: "OriginalWebServer"
    ports:
      - "8080:80"
    volumes:
      - "./volumes/original_web_server:/usr/local/apache2/htdocs"
    networks:
      vpcbr:
        ipv4_address: "192.168.0.101"
    dns:
      - "192.168.0.100"
    dns_search:
      - "poc.exemplo"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    restart: "always"

  attacker_web_server:
    image: "httpd:2.4"
    container_name: "AttackerWebServer"
    ports:
      - "8081:80"
    volumes:
      - "./volumes/attacker_web_server/:/usr/local/apache2/htdocs"
    networks:
      vpcbr:
        ipv4_address: "192.168.0.102"
    dns:
      - "192.168.0.100"
    dns_search:
      - "poc.exemplo"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    restart: "always"

  original_mail_server:
    image: "arvieira/mailserver"
    container_name: "OriginalMailServer"
    volumes:
      - "./volumes/mail_server/original/postfix:/etc/postfix"
      - "./volumes/mail_server/original/mailname:/etc/mailname"
      - "./volumes/mail_server/original/dovecot:/etc/dovecot"
    networks:
      vpcbr:
        ipv4_address: "192.168.0.103"
    dns:
      - "192.168.0.100"
    dns_search:
      - "poc.exemplo"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    restart: "always"

  attacker_mail_server:
    image: "arvieira/mailserver"
    container_name: "AttackerMailServer"
    volumes:
      - "./volumes/mail_server/attacker/postfix:/etc/postfix"
      - "./volumes/mail_server/attacker/mailname:/etc/mailname"
      - "./volumes/mail_server/attacker/dovecot:/etc/dovecot"
    networks:
      vpcbr:
        ipv4_address: "192.168.0.104"
    dns:
      - "192.168.0.100"
    dns_search:
      - "poc.exemplo"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    restart: "always"

  dns_server:
    image: "ubuntu/bind9:9.18-22.04_beta"
    hostname: "ns1.poc.exemplo"
    container_name: "DNSServer"
    environment:
      - "TZ=UTC"
      - "BIND9_USER=bind"
    volumes:
      - "./volumes/dns_server/bind:/etc/bind"
      - "./volumes/dns_server/cache:/var/cache/bind"
      - "./volumes/dns_server/records:/var/lib/bind"
    networks:
      vpcbr:
        ipv4_address: "192.168.0.100"
    dns:
      - "192.168.0.100"
    dns_search:
      - "poc.exemplo"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    restart: "always"

  client:
    image: "arvieira/client"
    container_name: "client"
    ports:
      - "22:22"
    environment:
      - "MAIL=~/Maildir"
    volumes:
      - "./volumes/client_ssh_server:/home/perito/volume"
      - "./volumes/mail_server/client/s-nail.rc:/etc/s-nail.rc"
      - "./volumes/mail_server/client/muttrc:/home/perito/.muttrc"
    networks:
      vpcbr:
        ipv4_address: "192.168.0.200"
    dns:
      - "192.168.0.100"
    dns_search:
      - "poc.exemplo"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    restart: "always"

networks:
  vpcbr:
    driver: "bridge"
    ipam:
      config:
        - subnet: "192.168.0.0/24"
          gateway: "192.168.0.1"
